// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usersTableQuery.sql

package usersTableQuery

import (
	"context"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (username, email, auth_id) VALUES
($1,$2,$3)
ON CONFLICT (username) DO NOTHING
`

type InsertUserParams struct {
	Username string
	Email    string
	AuthID   string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.Username, arg.Email, arg.AuthID)
	return err
}
